// Command gen-cli-reference writes docs/cli-reference.md from the real command tree, so the
// reference always matches `tuzy <cmd> --help` (CI fails if the file is stale).
//
//	go run ./tools/gen-cli-reference > docs/cli-reference.md
package main

import (
	"fmt"
	"os"
	"strings"

	"github.com/spf13/cobra"

	"github.com/nhtera/tuzy/internal/cli"
)

func main() {
	root := cli.NewRootCmd()
	root.DisableAutoGenTag = true
	var b strings.Builder
	b.WriteString("# tuzy CLI reference\n\n<!-- Generated by `go run ./tools/gen-cli-reference > docs/cli-reference.md`. Do not edit. -->\n\n")
	var walk func(c *cobra.Command, depth int)
	walk = func(c *cobra.Command, depth int) {
		if c.Hidden || c.Name() == "help" || strings.HasPrefix(c.Name(), "__") {
			return
		}
		if c != root {
			fmt.Fprintf(&b, "%s `%s`\n\n", strings.Repeat("#", min(depth+1, 4)), c.CommandPath())
			if c.Long != "" {
				b.WriteString(c.Long + "\n\n")
			} else if c.Short != "" {
				b.WriteString(c.Short + ".\n\n")
			}
			usage := strings.TrimRight(c.UsageString(), "\n")
			b.WriteString("```text\n" + usage + "\n```\n\n")
		}
		for _, sub := range c.Commands() {
			walk(sub, depth+1)
		}
	}
	walk(root, 0)
	if _, err := os.Stdout.WriteString(b.String()); err != nil {
		os.Exit(1)
	}
}
