/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false src/worker-configuration.d.ts` (hash: 8e97d498c9909c786737379b4c8b69d2)
interface __BaseEnv_Env {
	NAMES_KV: KVNamespace;
	DB: D1Database;
	EMAIL: SendEmail;
	RL_OTP_IP: RateLimit;
	RL_OTP_EMAIL: RateLimit;
	RL_API: RateLimit;
	RL_CONNECT: RateLimit;
	RL_TUNNEL: RateLimit;
	RL_ABUSE: RateLimit;
	BASE_DOMAIN: string;
	HEAD_TIMEOUT_SECONDS: string;
	MAX_STREAM_SECONDS: string;
	DEAD_SOCKET_SECONDS: string;
	CREDIT_TIMEOUT_SECONDS: string;
	LONG_STREAM_AFTER_SECONDS: string;
	HELLO_TIMEOUT_SECONDS: string;
	EMAIL_DRIVER: string;
	EMAIL_FROM: string;
	DAILY_SEND_BUDGET: string;
	QUARANTINE_THRESHOLD: string;
	LONG_STREAM_BUDGET_SECONDS: string;
	ADMIN_EMAIL: string;
	INTERSTITIAL_SECRET: string;
	ALLOW_LOG_EMAIL?: string; // test-only (vitest bindings); hand-added, keep on regenerate
	TUNNEL: DurableObjectNamespace<import("./index").TunnelObject>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./index");
		durableNamespaces: "TunnelObject";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "BASE_DOMAIN" | "HEAD_TIMEOUT_SECONDS" | "MAX_STREAM_SECONDS" | "DEAD_SOCKET_SECONDS" | "CREDIT_TIMEOUT_SECONDS" | "LONG_STREAM_AFTER_SECONDS" | "HELLO_TIMEOUT_SECONDS" | "EMAIL_DRIVER" | "EMAIL_FROM" | "DAILY_SEND_BUDGET" | "QUARANTINE_THRESHOLD" | "LONG_STREAM_BUDGET_SECONDS" | "ADMIN_EMAIL" | "INTERSTITIAL_SECRET">> {}
}
